Matrix Operations Project

Create two 3×3 matrices and:

Add, subtract, multiply, and find dot product

Find determinant, transpose, and inverse
👉 Concepts used: np.dot, np.linalg.det, np.transpose, np.linalg.inv

In [1]:
import numpy as np

In [10]:
arr1 = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [7, 9, 11]
])

arr2 = np.array([
    [5, 8, 2],
    [6, 9, 3],
    [4, 7, 1]
])



print("addtion in two matrix ",arr1+arr2)
print("multiplication in two matrix:",arr1*arr2)
print("Dot product of two matrix:",np.dot(arr1,arr2))
print("transpose arr1:\n",np.transpose(arr1))
print("Determinant of arr1:",np.linalg.det(arr1))
print("inverse of arr2:",np.linalg.inv(arr2))


addtion in two matrix  [[ 7 12  8]
 [ 7 12  8]
 [11 16 12]]
multiplication in two matrix: [[10 32 12]
 [ 6 27 15]
 [28 63 11]]
Dot product of two matrix: [[ 58  94  22]
 [ 43  70  16]
 [133 214  52]]
transpose arr1:
 [[ 2  1  7]
 [ 4  3  9]
 [ 6  5 11]]
Determinant of arr1: 0.0
inverse of arr2: [[-2.25179981e+15  1.12589991e+15  1.12589991e+15]
 [ 1.12589991e+15 -5.62949953e+14 -5.62949953e+14]
 [ 1.12589991e+15 -5.62949953e+14 -5.62949953e+14]]
