In [ ]:
import numpy as np

# Step 1: Create array of Celsius temperatures
celsius = np.array([0, 10, 25, 37, 100])
print("Celsius Temperatures:", celsius)

# Step 2: Convert to Fahrenheit (element-wise)
fahrenheit = (celsius * 9/5) + 32

# Step 3: Convert to Kelvin (element-wise)
kelvin = celsius + 273.15

# Step 4: Display results
print("\nFahrenheit Temperatures:", fahrenheit)
print("Kelvin Temperatures:", kelvin)

# Optional: Combine all in one 2D array for better view
combined = np.column_stack((celsius, fahrenheit, kelvin))
print("\nCombined Temperature Table (C, F, K):\n", combined)


Celsius Temperatures: [  0  10  25  37 100]

Fahrenheit Temperatures: [ 32.   50.   77.   98.6 212. ]
Kelvin Temperatures: [273.15 283.15 298.15 310.15 373.15]

Combined Temperature Table (C, F, K):
 [[  0.    32.   273.15]
 [ 10.    50.   283.15]
 [ 25.    77.   298.15]
 [ 37.    98.6  310.15]
 [100.   212.   373.15]]
