# Numpy Basics
Today I learn about numpy arrays, properties, and reshaping.

## Key Concepts
1. Array creation
2. List vs Numpy array
3. Array properties


In [1]:
import numpy as np

## Creating array from list

In [2]:
arr_1d=np.array([1,2,3,4,5])
print("arr_1d:",arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print("arr_2d:",arr_2d)



arr_1d: [1 2 3 4 5]
arr_2d: [[1 2 3]
 [4 5 6]]


## List vs numpy array


In [3]:
py_list=[1,2,3]
print("py list multiplication:",py_list*2)

np_array=np.array([1,2,3])
print("numpy array multiplication:",np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(100000)]
print("\n List op time:",time.time()-start)

start=time.time()
np_array=np.arange(100000)*2
print("\n numpy operation time:",time.time()-start)


py list multiplication: [1, 2, 3, 1, 2, 3]
numpy array multiplication: [2 4 6]

 List op time: 0.014611244201660156

 numpy operation time: 0.0010132789611816406


### creating array from scratch

In [4]:
zeros=np.zeros((3,4))
print("Zeros Array:",zeros)

ones=np.ones((2,3))
print("ones array",ones)

full=np.full((2,2),7)
print("Full array",full)


random=np.random.random((2,3))
print("Random array",random)

sequence=np.arange(0,10,2)
print("sequence array",sequence)

Zeros Array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array [[1. 1. 1.]
 [1. 1. 1.]]
Full array [[7 7]
 [7 7]]
Random array [[0.97144371 0.54318235 0.69328803]
 [0.4463622  0.09482076 0.38402666]]
sequence array [0 2 4 6 8]


### vector,metrix and tensor


In [5]:
vector=np.array([1,2,3])
print("Vector is",vector)

metrix=np.array([[1,2,3],[1,2,3]])
print("Metrix:",metrix)

tensor=np.array([[[1,2],[3,4]],[[4,5],[8,9]]])
print("tensor:",tensor)

Vector is [1 2 3]
Metrix: [[1 2 3]
 [1 2 3]]
tensor: [[[1 2]
  [3 4]]

 [[4 5]
  [8 9]]]


### Array properties

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("DType",arr.dtype)


shape: (2, 3)
Dimension 2
Size 6
DType int64


### Array Reshaping


In [7]:
arr=np.arange(12)
print("Original array:",arr)

reshaped=arr.reshape((3,4))
print("\nreshaped array:",reshaped)

# return copy array instead of original
flattened=reshaped.flatten()
print("\nFlatten array:",flattened)

# return original array instead of copy
raveled=flattened.ravel()
print("ravaeled array:",raveled)

transpose=reshaped.T
print("Transpose array:",transpose)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flatten array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravaeled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
