

# 🟢 NumPy Array Operations – Index of Concepts

## 1️⃣ 1D Array Operations

* Array creation (`np.array`)
* Basic slicing (`arr[start:end]`)
* Step slicing (`arr[start:end:step]`)
* Negative indexing (`arr[-n]`)

## 2️⃣ 2D Array Operations

* 2D array creation (`np.array([[…]])`)
* Access specific element (`arr_2d[row][col]`)
* Access entire row (`arr_2d[row]`)
* Access entire column (`arr_2d[:,col]`)

## 3️⃣ Sorting

* Sort 1D array (`np.sort(arr)`)
* Sort 2D array by column (`np.sort(arr_2d, axis=0)`)

## 4️⃣ Filtering Arrays

* Filter with condition (`arr[condition]`)
* Select even numbers (`arr[arr % 2 == 0]`)
* Boolean mask filtering (`mask = arr > value; arr[mask]`)

## 5️⃣ Fancy Indexing & `np.where`

* Fancy indexing (`arr[[i,j,k]]`)
* `np.where(condition)` → indices where condition is True
* `np.where(condition, x, y)` → conditional array based on condition

## 6️⃣ Adding & Removing Data

* Concatenate arrays (`np.concatenate((arr1, arr2))`)
* Add row to 2D array (`np.vstack((arr, new_row))`)
* Add column to 2D array (`np.hstack((arr, new_col))`)
* Delete element (`np.delete(arr, index)`)

## 7️⃣ Array Compatibility

* Check shapes (`a.shape == b.shape`)

---


In [2]:
import numpy as np


In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing:",arr[2:4])
print("With step slicing:",arr[2:7:2])
print("nagative indexing:",arr[-5])

Basic slicing: [3 4]
With step slicing: [3 5 7]
nagative indexing: 5


### 2D arr slicing

In [4]:
arr_2d=np.array([[1,2,8],[3,4,6],[7,9,10]])
print("Specific element:",arr_2d[1][2])
print("Entire Row:",arr_2d[1])
print("Entrie Column:",arr_2d[:,2])

Specific element: 6
Entire Row: [3 4 6]
Entrie Column: [ 8  6 10]


### Sorting

In [5]:
unsorted_array=np.array([1,6,3,5,8,2,9,4,7])
print("sorted array:",np.sort(unsorted_array))

arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column:",np.sort(arr_2d_unsorted,axis=0))

sorted array: [1 2 3 4 5 6 7 8 9]
sorted 2d array by column: [[1 1]
 [2 2]
 [3 3]]


### Filter


In [6]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_num=numbers[numbers%2==0]
print("Even numbers:",even_num)

Even numbers: [ 2  4  6  8 10]


### filter with mask


In [7]:
mask=numbers>5
print("Number with mask filter:",numbers[mask])

Number with mask filter: [ 6  7  8  9 10]


### fancy indexing vs np.where()


In [9]:
indices=[2,4,6]
print(numbers[indices])

where_result=np.where(numbers>5)
print(where_result)
print("Np where:",numbers[where_result])

[3 5 7]
(array([5, 6, 7, 8, 9]),)
Np where: [ 6  7  8  9 10]


In [16]:
conditional_array = np.where(numbers > 3, numbers*2, numbers)
print("Conditional array:", conditional_array)


Conditional array: [ 1  2  3  8 10 12 14 16 18 20]


### Adding and Removing Data


In [20]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
conacate_array=np.concatenate((arr1,arr2))
print(conacate_array)

[1 2 3 4 5 6]


### Array compatiblity

In [24]:
a=np.array([1,2,3])
b=np.array([6,7,8])
c=np.array([4,5,9])
print("compatiblity shapes:",a.shape==b.shape)

compatiblity shapes: True


In [29]:
original=np.array([[1,2],[3,4]])
new_row=np.array([5,6])
with_new_row=np.vstack((original,new_row))
print("array with new Row:",with_new_row)

new_column=np.array([[7],[8]])
with_new_column=np.hstack((original,new_column))
print("array with new Row:",with_new_column)

array with new Row: [[1 2]
 [3 4]
 [5 6]]
array with new Row: [[1 2 7]
 [3 4 8]]


In [30]:
arr=np.array([1,2,3,4,5,6])
deleted=np.delete(arr,2)
print("Deleted Element:",deleted)

Deleted Element: [1 2 4 5 6]
