### Advance indexing in numpy

In [ ]:
import numpy as np 
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(x)
print('The new array is :\n', y)

[[1 2]
 [3 4]
 [5 6]]
The new array is :
 [1 4 5]


In [5]:
a = np.arange(12).reshape(4,3)  # shape (4,3)
rows = [3,1,2]
print(a[rows])   # select those rows


[[ 9 10 11]
 [ 3  4  5]
 [ 6  7  8]]


In [9]:
M = np.arange(20).reshape(5,4)
rows = [0,2,4]
print(M)
sub = M[rows]         
print(sub)
print(sub[sub % 3 == 0]) 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]
[ 0  3  9 18]


In [12]:
arr = np.arange(6)
idx = [1,3,4]
print(arr[idx])
arr[idx] = -1
print(arr)


[1 3 4]
[ 0 -1  2 -1 -1  5]


In [14]:
a = np.arange(6)
v = a[1:4]   # view
print(v)
v[0] = 99
print(a)     # original changed

a = np.arange(6)
w = a[[1,2,3]]   # copy
w[0] = 88
print(a)         # unchanged


[1 2 3]
[ 0 99  2  3  4  5]
[0 1 2 3 4 5]
